###

POST https://api.github.com/repos/singleparty/cd/dispatches HTTP/1.1
Content-Type: application/json
Accept: application/vnd.github.v3+json
Authorization: token ghp_cT    JrvHH9ZGUa4G9bUPFIVN0T16WrIr2J5oUZ

{"event_type":"manually"}